### ISSUE TITLE
1.21.3 - Noel - No Working

### ISSUE THREAD

**Issue by SilentTree4** [YourMediocrePal/Noel#9]
Hello, when i tried to use the Noel mod it would send me back to the launcher and give me a crash report. I tried to used it on a instalation with no mods but it still didnt work. I hope you fix this because this mod looks super good

Here is the crash report. 

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2024-11-30 16:56:40
Description: Bootstrap

java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1690 failed
	at knot//net.minecraft.class_1299.method_64432(class_1299.java:869)
	at knot//net.minecraft.class_1299.<clinit>(class_1299.java:202)
	at knot//net.minecraft.class_10192.method_64017(class_10192.java:63)
	at knot//net.minecraft.class_1802.method_63920(class_1802.java:528)
	at knot//net.minecraft.class_1802.method_63752(class_1802.java:1508)
	at knot//net.minecraft.class_1802.method_63751(class_1802.java:1527)
	at knot//net.minecraft.class_1802.method_51348(class_1802.java:1551)
	at knot//net.minecraft.class_1802.method_63748(class_1802.java:1527)
	at knot//net.minecraft.class_1802.method_7993(class_1802.java:1523)
	at knot//net.minecraft.class_1802.method_58096(class_1802.java:1508)
	at knot//net.minecraft.class_1802.<clinit>(class_1802.java:528)
	at knot//net.minecraft.class_6089.method_9530(class_6089.java:65)
	at knot//net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1097)
	at knot//net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1093)
	at knot//net.minecraft.class_4970.method_9549(class_4970.java:361)
	at knot//net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1368)
	at knot//net.minecraft.class_4970$class_4971.method_26200(class_4970.java:908)
	at knot//net.minecraft.class_2246.<clinit>(class_2246.java:1311)
	at knot//net.minecraft.class_2358.method_10199(class_2358.java:336)
	at knot//net.minecraft.class_2966.method_12851(class_2966.java:53)
	at knot//net.minecraft.client.main.Main.main(Main.java:138)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1690 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 24 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 28 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.terraform-boats.json:MixinBoatEntity from mod terraform-wood-api-v1] from phase [DEFAULT] in config [mixins.terraform-boats.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 31 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyArg annotation on terraformWood$replacePlanksDropItem could not find any targets matching 'Lnet/minecraft/class_1690;method_5623(DZLnet/minecraft/class_2680;Lnet/minecraft/class_2338;)V' in net/minecraft/class_1690. Using refmap terraform-wood-api-v1-refmap.json [INJECT_PREPARE Applicator Phase -> mixins.terraform-boats.json:MixinBoatEntity from mod terraform-wood-api-v1 -> Prepare Injections -> modify$bic000$terraform-wood-api-v1$terraformWood$replacePlanksDropItem(Lnet/minecraft/class_1935;)Lnet/minecraft/class_1935; -> Parse ->  -> Validate Targets]
	at org.spongepowered.asm.mixin.injection.selectors.TargetSelectors.validate(TargetSelectors.java:346)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:369)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:340)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:331)
	at org.spongepowered.asm.mixin.injection.struct.ModifyArgInjectionInfo.<init>(ModifyArgInjectionInfo.java:47)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:196)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:664)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1399)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:731)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:315)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 31 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at knot//net.minecraft.class_1299.method_64432(class_1299.java:869)
	at knot//net.minecraft.class_1299.<clinit>(class_1299.java:202)
	at knot//net.minecraft.class_10192.method_64017(class_10192.java:63)
	at knot//net.minecraft.class_1802.method_63920(class_1802.java:528)
	at knot//net.minecraft.class_1802.method_63752(class_1802.java:1508)
	at knot//net.minecraft.class_1802.method_63751(class_1802.java:1527)
	at knot//net.minecraft.class_1802.method_51348(class_1802.java:1551)
	at knot//net.minecraft.class_1802.method_63748(class_1802.java:1527)
	at knot//net.minecraft.class_1802.method_7993(class_1802.java:1523)
	at knot//net.minecraft.class_1802.method_58096(class_1802.java:1508)
	at knot//net.minecraft.class_1802.<clinit>(class_1802.java:528)
	at knot//net.minecraft.class_6089.method_9530(class_6089.java:65)
	at knot//net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1097)
	at knot//net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1093)
	at knot//net.minecraft.class_4970.method_9549(class_4970.java:361)
	at knot//net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1368)
	at knot//net.minecraft.class_4970$class_4971.method_26200(class_4970.java:908)
	at knot//net.minecraft.class_2246.<clinit>(class_2246.java:1311)
	at knot//net.minecraft.class_2358.method_10199(class_2358.java:336)
	at knot//net.minecraft.class_2966.method_12851(class_2966.java:53)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.26100.2454 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.26100.2033 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.26100.1591 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.26100.2033 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.26100.2454 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.26100.2454 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.24090.11 (26d75470953920f90fd0438874501e9d9a31e621):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.26100.1882 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		POWRPROF.dll:Power Profile Helper DLL:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.26100.2454 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.26100.1301 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.26100.2033 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.26100.2454 (WinBuild.160101.0800):Microsoft Corporation
		dxcore.dll:DXCore:10.0.26100.2454 (WinBuild.160101.0800):Microsoft Corporation
		extnet.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.26100.2161 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.26100.2454 (WinBuild.160101.0800):Microsoft Corporation
		java.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		javaw.exe:OpenJDK Platform binary:21.0.3.0:Microsoft
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		jli.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		jna8223926623960301739.dll:JNA native library:7.0.0:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		jvm.dll:OpenJDK 64-Bit server VM:21.0.3.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.26100.1591 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		mc-sec-plugin-x64.dll:McAfee Antivirus Core Plugin:1.3.1504.0:McAfee, LLC
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.26100.1882 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.26100.1882 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.26100.1591 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		nio.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:NT Layer DLL:10.0.26100.2454 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows System Performance Objects DLL:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.26100.1301 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.26100.2454 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.26100.1882 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		win32u.dll:Win32u:10.0.26100.2454 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.26100.1457 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.26100.1882 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.26100.1882 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
Stacktrace:
	at knot//net.minecraft.client.main.Main.main(Main.java:138)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.21.3
	Minecraft Version ID: 1.21.3
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 253615040 bytes (241 MiB) / 570425344 bytes (544 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 7600 6-Core Processor              
	Identifier: AuthenticAMD Family 25 Model 97 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 64.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.11020.16
	Graphics card #1 name: NVIDIA GeForce RTX 4060
	Graphics card #1 vendor: NVIDIA
	Graphics card #1 VRAM (MiB): 8188.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 32.0.15.5612
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 4.80
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 4.80
	Memory slot #1 type: Unknown
	Virtual memory max (MiB): 32333.02
	Virtual memory used (MiB): 19556.20
	Swap memory total (MiB): 16384.00
	Swap memory used (MiB): 1076.59
	Space in storage for jna.tmpdir (MiB): available: 64414.38, total: 975751.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 64414.38, total: 975751.00
	Space in storage for io.netty.native.workdir (MiB): available: 64414.38, total: 975751.00
	Space in storage for java.io.tmpdir (MiB): available: 64414.38, total: 975751.00
	Space in storage for workdir (MiB): available: 64414.38, total: 975751.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		cavedust: Cave Dust 3.0.1
			kirin: Kirin UI 1.19.3+1.21.3
		cicada: CICADA 0.9.1+1.21.2-and-above
		cloth-config: Cloth Config v16 16.0.141
			cloth-basic-math: cloth-basic-math 0.6.1
		elementa: Elementa 670
		essential: Essential 1.3.5.3
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.3
		fabric-api: Fabric API 0.108.0+1.21.3
			fabric-api-base: Fabric API Base 0.4.49+fd37071f40
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.80+fd37071f40
			fabric-biome-api-v1: Fabric Biome API (v1) 14.0.6+fd37071f40
			fabric-block-api-v1: Fabric Block API (v1) 1.0.28+fd37071f40
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.16+fd37071f40
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 2.0.3+fd37071f40
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.23+fd37071f40
			fabric-command-api-v1: Fabric Command API (v1) 1.2.57+f71b366f40
			fabric-command-api-v2: Fabric Command API (v2) 2.2.36+fd37071f40
			fabric-commands-v0: Fabric Commands (v0) 0.2.74+df3654b340
			fabric-content-registries-v0: Fabric Content Registries (v0) 9.1.7+fd37071f40
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.2+7f945d5b40
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.2+84ebbb0e40
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.3+fd37071f40
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.3.0+e9d2cfc840
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 21.0.16+fd37071f40
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.7+fd37071f40
			fabric-entity-events-v1: Fabric Entity Events (v1) 2.0.7+825023f840
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 2.0.11+c2c3ac4740
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.59+fd37071f40
			fabric-item-api-v1: Fabric Item API (v1) 11.1.6+fd37071f40
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.16+fd37071f40
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.53+fd37071f40
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.51+df3654b340
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.0+6da5ef6940
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.25+3f89f5a540
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.13+fd37071f40
			fabric-message-api-v1: Fabric Message API (v1) 6.0.20+fd37071f40
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 3.0.8+fd37071f40
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.4+fd37071f40
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 17.0.8+fd37071f40
			fabric-particles-v1: Fabric Particles (v1) 4.0.9+fd37071f40
			fabric-recipe-api-v1: Fabric Recipe API (v1) 7.0.3+fd37071f40
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.2.1+fd37071f40
			fabric-renderer-api-v1: Fabric Renderer API (v1) 4.0.4+fd37071f40
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.9.4+fd37071f40
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.54+73761d2e40
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.14+fd37071f40
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.82+df3654b340
			fabric-rendering-v1: Fabric Rendering (v1) 8.0.6+fd37071f40
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.8+fd37071f40
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.0.6+fd37071f40
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.33+fd37071f40
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.99+fd37071f40
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.29+fd37071f40
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.2+fd37071f40
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.8+fd37071f40
		fabric-language-kotlin: Fabric Language Kotlin 1.10.19+kotlin.1.9.23
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		fallingleaves: Falling Leaves 1.16.3
		iris: Iris 1.8.0+mc1.21.3
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		malilib: MaLiLib 0.22.0
		minecraft: Minecraft 1.21.3
		noel: Noel 1.6
			terraform-wood-api-v1: Terraform Wood API (v1) 11.0.0
		org_jetbrains_annotations: annotations 23.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.23
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.23
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.23
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.23
		org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.2
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.0
		org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		sodium: Sodium 0.6.0-beta.5+mc1.21.3
		universalcraft: UniversalCraft 365
		vigilance: Vigilance 306
		voicechat: Simple Voice Chat 1.21.3-2.5.26
		yet_another_config_lib_v3: YetAnotherConfigLib 3.6.1+1.21.2-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Launched Version: fabric-loader-0.16.9-1.21.3
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GFLW Platform: <error>
	GL Caps: ERR
	GL debug messages: <disabled>
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en_US
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: <unknown>

**Comment by YourMediocrePal** [comment]
Hi! Thanks for the report. Looks like one of the APIs is incompatible with 1.21.3. I will make a fix! Happy holidays.
